sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Fb4CwfhEIw8PPRDBPLUzPRbCrL/+bPRQzSOFjlP5KkdwvOXDhyiVk8ww2lWS0R6calYsuhhQ4uRAOHK+r3wQdR2fbbyuxlPRuwckylvsRgk1sbD6Y3hiDrcD3mj1r8W0AUH7gQLnfNKfKaTpNMICOJ250QBoGQoRBU/oAUeWFjahHwXwNReWiEAo85FaAJ3rXNCziqy/Daq0pwAncBQelzK2GIxwTjpwGe7z0Ylvlc86j0Krs/mt+92AAZNJyHz/BYjzybGndvPrlJPZu6VKZ70ZZ6e/7dIS0de8YfETy4iHYZb+SkNLv64v15KOgKaPPiD7ohdZDIB1F8Wi3sCSpY6/6bXF9Hf5lwfy/cODVmQIobEnKSvQf8vpa+JzI88n7oE2/yb6E5AGLsvml4VChyrPtU7pEtghe0fOHnQyHyFDpaajR//OFX9xG1pjhweTStnJOhyTxYhlbsVTxKLR6nlWIEjZlv5VC4KSxkaxQiD/BBmTZlnPfAEcBB3T4Ug8MZs9rZWITIDyObdSYS0dV4hmhT59NzFvvTN/ZbMHNEtwqaCwLcPLEl/OymxAfo5eDgTLQBrdBttN6VuqB2sj8U0yx7E4rnaMSqZNzwW8ozBSDBGig6Q/Z/f80Eevo7RXsVpVxAMu9xjMgxUmEBRhPSlufg0tcc0PXKRp3tWiiIg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Right-of-Way-Volume-06_6248
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy